name: Update GitHub Project Field

on:
  workflow_dispatch:  # ✅ Allows manual trigger in GitHub Actions

permissions:
  contents: write
  issues: write

jobs:
  update-project-field:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Field
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ✅ Uses Secret Instead of Hardcoding
        run: |
          PROJECT_ID="PVT_kwHOBffn_c4Ay8TW"  # ✅ Your GitHub Project ID
          ITEM_ID="PVTF_lAHOBffn_c4Ay8TWzgo0NbQ"  # ✅ Correct Project Item ID
          FIELD_ID="171193780"  # ✅ Field ID for "testing"
          FIELD_VALUE="10"  # ✅ Ensure this matches the field type

          echo "Updating Project Field for Item ID: $ITEM_ID..."

          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
          -H "Content-Type: application/json" \
          --data "{\"query\": \"mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
            updateProjectV2ItemFieldValue(
              input: {
                projectId: $projectId,
                itemId: $itemId,
                fieldId: $fieldId,
                value: { number: $value }  # ✅ Fixed JSON formatting
              }
            ) {
              projectV2Item {
                id
              }
            }
          }\", \"variables\": {\"projectId\": \"$PROJECT_ID\", \"itemId\": \"$ITEM_ID\", \"fieldId\": \"$FIELD_ID\", \"value\": $FIELD_VALUE}}" \
          https://api.github.com/graphql

          echo "✅ Project field updated successfully!"
