name: Update GitHub Project Field

on:
  workflow_dispatch:  # ✅ Allows manual trigger in GitHub Actions

permissions:
  contents: write
  issues: write

jobs:
  update-project-field:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Field
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ✅ Uses Secret Instead of Hardcoding
        run: |
          PROJECT_ID="PVT_kwHOBffn_c4Ay8TW"  # ✅ Your GitHub Project ID
          ITEM_ID="PVTF_lAHOBffn_c4Ay8TWzgo0NbQ"  # ✅ Correct Project Item ID
          FIELD_ID="171193780"  # ✅ Field ID for "testing"
          FIELD_VALUE=10  # ✅ Ensures correct type (number)

          echo "Updating Project Field for Item ID: $ITEM_ID..."

          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
          -H "Content-Type: application/json" \
          --data-raw "$(jq -n --arg projectId "$PROJECT_ID" --arg itemId "$ITEM_ID" --arg fieldId "$FIELD_ID" --argjson value "$FIELD_VALUE" '{
            query: "mutation UpdateField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Float!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { number: $value }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }",
            variables: {
              projectId: $projectId,
              itemId: $itemId,
              fieldId: $fieldId,
              value: $value
            }
          }')" https://api.github.com/graphql

          echo "✅ Project field updated successfully!"
